from enum import Enum

class EnvVariables(Enum):
    MINIO_ENDPOINT = "MINIO_ENDPOINT"
    MINIO_ACCESS_KEY = "MINIO_ACCESS_KEY"
    MINIO_SECRET_KEY = "MINIO_SECRET_KEY"
    KAFKA_BOOSTRAP_SERVERS = "KAFKA_BOOSTRAP_SERVERS"